#!/usr/bin/env node
// Local held-out leak guard (ADR-027 §1), installed by `pnpm prepare-hooks`.
//
// Reads a denylist from $X402_HELDOUT_DIR/.denylist (default ~/x402-redteam-heldout/.denylist),
// which lives outside the repository and is regenerated by a maintainer from the held-out
// corpus. One term per line; blank lines and lines starting with "#" are ignored. Terms
// match case-insensitively and must not be flanked by letters or digits, so "<id>_v2" and
// "corpus/<id>.yaml" match "<id>".
//
// Modes:
//   (default)              staged file paths and contents (pre-commit hook)
//   --message-file <path>  a commit message (commit-msg hook)
//   --pre-push             commits about to be pushed, refs read from stdin (pre-push hook):
//                          each commit's message, the paths it touches and the lines it adds
//
// If the denylist file is absent the guard exits 0 without output, so contributors without
// the held-out corpus are unaffected. On a match it prints only locations (file and line
// number; a matching path is shown as "(file path withheld)") and exits 1. It never prints a
// matched term or the line containing it.

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

export function denylistPath(env = process.env) {
  const dir = env.X402_HELDOUT_DIR || join(homedir(), "x402-redteam-heldout");
  return join(dir, ".denylist");
}

/** @param {string} text */
export function parseDenylist(text) {
  return text
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l !== "" && !l.startsWith("#"));
}

/** @param {string[]} terms */
export function compileMatcher(terms) {
  if (terms.length === 0) return null;
  const escaped = terms.map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  return new RegExp(`(?<![A-Za-z0-9])(?:${escaped.join("|")})(?![A-Za-z0-9])`, "i");
}

/**
 * 1-based line numbers of `text` that contain a denylisted term.
 * @param {string} text
 * @param {RegExp | null} matcher
 */
export function matchingLines(text, matcher) {
  if (!matcher) return [];
  const lines = [];
  text.split("\n").forEach((line, i) => {
    if (matcher.test(line)) lines.push(i + 1);
  });
  return lines;
}

const ZERO_SHA = /^0+$/;

function git(args) {
  return execFileSync("git", args, { maxBuffer: 256 * 1024 * 1024 });
}

function isBinary(buf) {
  return buf.includes(0);
}

const WITHHELD = "(file path withheld)";

/** Display name for a path: the path itself, or a placeholder when the path matches. */
function shownPath(name, matcher, hits) {
  if (!matcher.test(name)) return name;
  hits.push(WITHHELD);
  return WITHHELD;
}

function scanStaged(matcher) {
  const names = git(["diff", "--cached", "--name-only", "--diff-filter=ACMR", "-z"])
    .toString("utf8")
    .split("\0")
    .filter(Boolean);
  const hits = [];
  for (const name of names) {
    const shown = shownPath(name, matcher, hits);
    const buf = git(["show", `:${name}`]);
    if (isBinary(buf)) continue;
    for (const line of matchingLines(buf.toString("utf8"), matcher)) hits.push(`${shown}:${line}`);
  }
  return hits;
}

/**
 * Lines added by one commit, with their file and line number in the new version. Hunk
 * bodies are consumed by the line counts in their "@@" header, so an added line whose text
 * starts with "++ " is read as content, not as a file header.
 */
export function addedLines(patch) {
  const out = [];
  let file = null;
  let lineNo = 0;
  let oldLeft = 0;
  let newLeft = 0;
  for (const line of patch.split("\n")) {
    if (oldLeft > 0 || newLeft > 0) {
      if (line.startsWith("+")) {
        if (file) out.push({ file, line: lineNo, text: line.slice(1) });
        lineNo++;
        newLeft--;
      } else if (line.startsWith("-")) {
        oldLeft--;
      } else if (line.startsWith(" ") || line === "") {
        lineNo++;
        oldLeft--;
        newLeft--;
      }
      // "\ No newline at end of file" consumes nothing.
      continue;
    }
    const hunk = /^@@ -\d+(?:,(\d+))? \+(\d+)(?:,(\d+))? @@/.exec(line);
    if (hunk) {
      oldLeft = hunk[1] === undefined ? 1 : Number(hunk[1]);
      lineNo = Number(hunk[2]);
      newLeft = hunk[3] === undefined ? 1 : Number(hunk[3]);
    } else if (line.startsWith("+++ ")) {
      file = line === "+++ /dev/null" ? null : line.slice(4).replace(/^b\//, "");
    }
  }
  return out;
}

function scanCommit(sha, matcher) {
  const short = sha.slice(0, 7);
  const hits = [];
  const message = git(["log", "-1", "--format=%B", sha]).toString("utf8");
  for (const line of matchingLines(message, matcher)) hits.push(`${short} commit message:${line}`);
  const names = git(["diff-tree", "--root", "--no-commit-id", "--name-only", "-r", "-z", sha])
    .toString("utf8")
    .split("\0")
    .filter(Boolean);
  const withheld = new Set(names.filter((n) => matcher.test(n)));
  for (const _ of withheld) hits.push(`${short} ${WITHHELD}`);
  const patch = git([
    "show",
    "--format=",
    "--unified=0",
    "--no-color",
    "--no-ext-diff",
    "--no-renames",
    sha,
  ]).toString("utf8");
  for (const a of addedLines(patch)) {
    if (matcher.test(a.text)) {
      hits.push(`${short} ${withheld.has(a.file) ? WITHHELD : a.file}:${a.line}`);
    }
  }
  return hits;
}

function scanPrePush(stdin, matcher) {
  const hits = [];
  for (const ref of stdin.split("\n").filter(Boolean)) {
    const [, localSha, , remoteSha] = ref.split(" ");
    if (!localSha || ZERO_SHA.test(localSha)) continue;
    const range =
      !remoteSha || ZERO_SHA.test(remoteSha)
        ? [localSha, "--not", "--remotes"]
        : [`${remoteSha}..${localSha}`];
    const shas = git(["rev-list", ...range])
      .toString("utf8")
      .split("\n")
      .filter(Boolean);
    for (const sha of shas) hits.push(...scanCommit(sha, matcher));
  }
  return hits;
}

function main(argv) {
  const path = denylistPath();
  if (!existsSync(path)) return 0;
  const matcher = compileMatcher(parseDenylist(readFileSync(path, "utf8")));
  if (!matcher) return 0;

  let hits;
  const msgIdx = argv.indexOf("--message-file");
  if (msgIdx >= 0) {
    const text = readFileSync(argv[msgIdx + 1], "utf8");
    hits = matchingLines(text, matcher).map((l) => `commit message:${l}`);
  } else if (argv.includes("--pre-push")) {
    hits = scanPrePush(readFileSync(0, "utf8"), matcher);
  } else {
    hits = scanStaged(matcher);
  }

  if (hits.length === 0) return 0;
  console.error(`held-out guard: ${hits.length} location(s) contain denylisted held-out content:`);
  for (const h of hits) console.error(`  ${h}`);
  console.error("Remove it before committing or pushing. Matched text is not printed.");
  return 1;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  process.exit(main(process.argv.slice(2)));
}
